// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/coder_project2.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class coder_project2 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Integer count=null;
  static {
    int $line=0;
    $line=4;
    $try:try {
      count=$defaultValue(Integer.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder_project2.class,null,$line);
    }
  }
  public static String answ=null;
  static {
    int $line=0;
    $line=5;
    $try:try {
      answ=$defaultValue(String.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder_project2.class,null,$line);
    }
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=8;
      Object Q=$fix(GCollections.asSet("q_","q0","q1","q2","q3","q4","q5","q$","B"));
      $line=10;
      Object \u03A3=$fix($opUnionY($opIntvlY('a','z'),GCollections.asSet(' ','$')));
      $line=11;
      Object \u0393=$fix($opUnionY($opUnionY($opIntvlY('a','z'),GCollections.asSet('*','$','@','#')),$opIntvlY('0','9')));
      $line=12;
      Object q=$fix("q0");
      $line=13;
      Object F=$fix(GCollections.asSet("q$"));
      $line=15;
      Object A=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q,F,new GMethod(coder_project2.class,"\u03B4"),new GMethod(coder_project2.class,"g"),new GMethod(coder_project2.class,"h")}));
      $line=16;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder_project2.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=24;
      if (($opEqualY(q,"q0")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
        $line=25;
        count=$cast(Integer.class,$fix(1));
        $line=26;
        $result="q2";
        if (true) break $try;
      }
      else {
        $line=27;
        if (($opEqualY(q,"q0")&&$opEqualY(\u03C3,' '))) {
          $line=28;
          count=$cast(Integer.class,$fix(1));
          $line=29;
          $result="q1";
          if (true) break $try;
        }
        else {
          $line=31;
          if (($opEqualY(q,"q1")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
            $line=32;
            $result="q2";
            if (true) break $try;
          }
          else {
            $line=33;
            if (($opEqualY(q,"q2")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
              $line=34;
              $result="q3";
              if (true) break $try;
            }
            else {
              $line=35;
              if (($opEqualY(q,"q3")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                $line=36;
                $result="q4";
                if (true) break $try;
              }
              else {
                $line=37;
                if (($opEqualY(q,"q4")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                  $line=38;
                  $result="q5";
                  if (true) break $try;
                }
                else {
                  $line=39;
                  if (($opEqualY(q,"q5")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                    $line=40;
                    $result="q2";
                    if (true) break $try;
                  }
                  else {
                    $line=42;
                    if (($opMembrY(q,GCollections.asSet("q2","q3","q4","q5"))&&$opEqualY(\u03C3,' '))) {
                      $line=43;
                      $result="q1";
                      if (true) break $try;
                    }
                    else {
                      $line=44;
                      if (($opMembrY(q,GCollections.asSet("q2","q3","q4","q5"))&&$opEqualY(\u03C3,'$'))) {
                        $line=45;
                        $result="q$";
                        if (true) break $try;
                      }
                      else {
                        $line=48;
                        $result="B";
                        if (true) break $try;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=51;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder_project2.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=54;
      $result="";
      if (true) break $try;
      $line=55;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder_project2.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=59;
      if (($opMembrY(q,GCollections.asSet("q0","q1","q2","q3","q4"))&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
        $line=60;
        $result=\u03C3;
        if (true) break $try;
      }
      else {
        $line=62;
        if (($opEqualY(q,"q2")&&$opEqualY(\u03C3,' '))) {
          $line=63;
          answ=$cast(String.class,$fix($opAdditY($opAdditY("###",$opModulY(count,3)),"*")));
          $line=64;
          count=$cast(Integer.class,$fix(1));
          $line=65;
          $result=answ;
          if (true) break $try;
        }
        else {
          $line=66;
          if (($opEqualY(q,"q3")&&$opEqualY(\u03C3,' '))) {
            $line=67;
            answ=$cast(String.class,$fix($opAdditY($opAdditY("##",$opModulY(count,3)),"*")));
            $line=68;
            count=$cast(Integer.class,$fix(1));
            $line=69;
            $result=answ;
            if (true) break $try;
          }
          else {
            $line=70;
            if (($opEqualY(q,"q4")&&$opEqualY(\u03C3,' '))) {
              $line=71;
              answ=$cast(String.class,$fix($opAdditY($opAdditY("#",$opModulY(count,3)),"*")));
              $line=72;
              count=$cast(Integer.class,$fix(1));
              $line=73;
              $result=answ;
              if (true) break $try;
            }
            else {
              $line=74;
              if (($opEqualY(q,"q5")&&$opEqualY(\u03C3,' '))) {
                $line=75;
                answ=$cast(String.class,$fix($opAdditY($opModulY(count,3),"*")));
                $line=76;
                count=$cast(Integer.class,$fix(1));
                $line=77;
                $result=answ;
                if (true) break $try;
              }
              else {
                $line=79;
                if (($opEqualY(q,"q2")&&$opEqualY(\u03C3,'$'))) {
                  $line=80;
                  answ=$cast(String.class,$fix($opAdditY($opAdditY("###",$opModulY(count,3)),"$")));
                  $line=81;
                  count=$cast(Integer.class,$fix(1));
                  $line=82;
                  $result=answ;
                  if (true) break $try;
                }
                else {
                  $line=83;
                  if (($opEqualY(q,"q3")&&$opEqualY(\u03C3,'$'))) {
                    $line=84;
                    answ=$cast(String.class,$fix($opAdditY($opAdditY("##",$opModulY(count,3)),"$")));
                    $line=85;
                    count=$cast(Integer.class,$fix(1));
                    $line=86;
                    $result=answ;
                    if (true) break $try;
                  }
                  else {
                    $line=87;
                    if (($opEqualY(q,"q4")&&$opEqualY(\u03C3,'$'))) {
                      $line=88;
                      answ=$cast(String.class,$fix($opAdditY($opAdditY("#",$opModulY(count,3)),"$")));
                      $line=89;
                      count=$cast(Integer.class,$fix(1));
                      $line=90;
                      $result=answ;
                      if (true) break $try;
                    }
                    else {
                      $line=91;
                      if (($opEqualY(q,"q5")&&$opEqualY(\u03C3,'$'))) {
                        $line=92;
                        answ=$cast(String.class,$fix($opAdditY($opModulY(count,3),"$")));
                        $line=93;
                        count=$cast(Integer.class,$fix(1));
                        $line=94;
                        $result=answ;
                        if (true) break $try;
                      }
                      else {
                        $line=96;
                        if (($opEqualY(q,"q5")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                          $line=97;
                          count=$cast(Integer.class,$fix($opAdditY(count,1)));
                          $line=98;
                          $result=$opAdditY("@",\u03C3);
                          if (true) break $try;
                        }
                        else {
                          $line=101;
                          $result="";
                          if (true) break $try;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=104;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder_project2.class,"h",$line);
    }
    return $result;
  }
}
