// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/decoder_project2.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class decoder_project2 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Integer count=null;
  static {
    int $line=0;
    $line=4;
    $try:try {
      count=$defaultValue(Integer.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,decoder_project2.class,null,$line);
    }
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=7;
      Object Q=$fix(GCollections.asSet("q_","q0","q1","q2","q3","q4","q5","q6","q2#","q3#","q4#","q$","B"));
      $line=10;
      Object \u03A3=$fix($opUnionY($opUnionY($opIntvlY('a','z'),GCollections.asSet('*','$','@','#')),$opIntvlY('0','9')));
      $line=11;
      Object \u0393=$fix($opUnionY($opIntvlY('a','z'),GCollections.asSet(' ','$')));
      $line=12;
      Object q=$fix("q0");
      $line=13;
      Object F=$fix(GCollections.asSet("q$"));
      $line=15;
      Object A=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q,F,new GMethod(decoder_project2.class,"\u03B4"),new GMethod(decoder_project2.class,"g"),new GMethod(decoder_project2.class,"h")}));
      $line=16;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,decoder_project2.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=23;
      if (($opEqualY(q,"q0")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
        $line=24;
        count=$cast(Integer.class,$fix(1));
        $line=25;
        $result="q2";
        if (true) break $try;
      }
      else {
        $line=26;
        if (($opEqualY(q,"q0")&&$opEqualY(\u03C3,' '))) {
          $line=27;
          count=$cast(Integer.class,$fix(1));
          $line=28;
          $result="q1";
          if (true) break $try;
        }
        else {
          $line=31;
          if (($opEqualY(q,"q1")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
            $line=32;
            $result="q2";
            if (true) break $try;
          }
          else {
            $line=33;
            if (($opEqualY(q,"q2")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
              $line=34;
              $result="q3";
              if (true) break $try;
            }
            else {
              $line=35;
              if (($opEqualY(q,"q3")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                $line=36;
                $result="q4";
                if (true) break $try;
              }
              else {
                $line=37;
                if (($opEqualY(q,"q4")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                  $line=38;
                  $result="q5";
                  if (true) break $try;
                }
                else {
                  $line=39;
                  if (($opEqualY(q,"q5")&&$opEqualY(\u03C3,'@'))) {
                    $line=40;
                    count=$cast(Integer.class,$fix($opAdditY(count,1)));
                    $line=41;
                    $result="q1";
                    if (true) break $try;
                  }
                  else {
                    $line=47;
                    if (($opEqualY(q,"q2")&&$opEqualY(\u03C3,'#'))) {
                      $line=48;
                      $result="q3#";
                      if (true) break $try;
                    }
                    else {
                      $line=49;
                      if (($opEqualY(q,"q3")&&$opEqualY(\u03C3,'#'))) {
                        $line=50;
                        $result="q4#";
                        if (true) break $try;
                      }
                      else {
                        $line=51;
                        if (($opEqualY(q,"q4")&&$opEqualY(\u03C3,'#'))) {
                          $line=52;
                          $result="q5";
                          if (true) break $try;
                        }
                        else {
                          $line=54;
                          if (($opEqualY(q,"q2#")&&$opEqualY(\u03C3,'#'))) {
                            $line=55;
                            $result="q3#";
                            if (true) break $try;
                          }
                          else {
                            $line=56;
                            if (($opEqualY(q,"q3#")&&$opEqualY(\u03C3,'#'))) {
                              $line=57;
                              $result="q4#";
                              if (true) break $try;
                            }
                            else {
                              $line=58;
                              if (($opEqualY(q,"q4#")&&$opEqualY(\u03C3,'#'))) {
                                $line=59;
                                $result="q5";
                                if (true) break $try;
                              }
                              else {
                                $line=61;
                                if (($opEqualY(q,"q5")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                                  $line=63;
                                  if (($opEqualY(\u03C3,'0')&&$opEqualY($opModulY(count,3),0))) {
                                    $line=64;
                                    $result="q6";
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=65;
                                    if (($opEqualY(\u03C3,'1')&&$opEqualY($opModulY(count,3),1))) {
                                      $line=66;
                                      $result="q6";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=67;
                                      if (($opEqualY(\u03C3,'2')&&$opEqualY($opModulY(count,3),2))) {
                                        $line=68;
                                        $result="q6";
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=70;
                                        $result="B";
                                        if (true) break $try;
                                      }
                                    }
                                  }
                                }
                                else {
                                  $line=72;
                                  if (($opEqualY(q,"q6")&&$opEqualY(\u03C3,'*'))) {
                                    $line=73;
                                    $result="q1";
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=74;
                                    if (($opEqualY(q,"q6")&&$opEqualY(\u03C3,'$'))) {
                                      $line=75;
                                      $result="q$";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=79;
                                      $result="B";
                                      if (true) break $try;
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=82;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,decoder_project2.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=85;
      $result="";
      if (true) break $try;
      $line=86;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,decoder_project2.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=91;
      if (($opMembrY(q,GCollections.asSet("q0","q1","q2","q3","q4"))&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
        $line=92;
        $result=\u03C3;
        if (true) break $try;
      }
      else {
        $line=94;
        if (($opEqualY(q,"q6")&&$opEqualY(\u03C3,'*'))) {
          $line=95;
          count=$cast(Integer.class,$fix(1));
          $line=96;
          $result=" ";
          if (true) break $try;
        }
        else {
          $line=98;
          if (($opEqualY(q,"q6")&&$opEqualY(\u03C3,'$'))) {
            $line=99;
            $result="$";
            if (true) break $try;
          }
          else {
            $line=102;
            $result="";
            if (true) break $try;
          }
        }
      }
      $line=105;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,decoder_project2.class,"h",$line);
    }
    return $result;
  }
}
