/*
Project 1
@authors: Federico Melo Barrero, f.melo, 202021525
		  Germán Alberto Rojas Cetina, g.rojasc, 202013415
*/


options 
{
	LOOKAHEAD=1; 
	IGNORE_CASE=true;
	STATIC = false;
}


PARSER_BEGIN(Robot)

package uniandes.lym.robot.control;

import uniandes.lym.robot.kernel.*;
import uniandes.lym.robot.view.Console;
 
import java.awt.Point;
import java.io.*;
import java.util.*;

@SuppressWarnings("serial")
public class Robot 
{
	private RobotWorldDec world;


	void setWorld(RobotWorld w) {
		world = (RobotWorldDec) w;	
	}


	private String salida = new String();

	private Hashtable<String, Integer> vars = new Hashtable<String, Integer>();
	private ArrayList<String> declaredVars = new ArrayList<String>();
}

PARSER_END(Robot)


SKIP:
{
		" "
	|	"\r"
	|	"\t"
	|	"\n"
}


/* Commands */
TOKEN: 
{
		< STEP: "step" >
	|	< JUMP: "jump" >
	|	< JUMPTO: "jumpTo" >
	|	< VEER: "veer" >
	|	< LOOK: "look" >
	|	< DROP: "drop" >
	|	< GRAB: "grab" >
	|	< GET: "get" >
	|	< FREE: "free" >
	|	< POP: "pop" >
	| 	< DMOVE:  "Dmove" >
	|	< OMOVE:  "Omove" >
}


/* Control structures */
TOKEN :
{
		< IF: "if" >
	|	< FI: "fi" >
	|	< ELSE: "else" >
	| 	< WHILE: "while" >
	|	< DO: "do" >
	| 	< OD: "od" >
	|	< REPEATTIMES: "repeatTimes" >
	|	< PER : "per" >
}


/* Conditions */
TOKEN :
{
		< ISFACING : "isfacing" >
	| 	< ISVALID: "isValid" >
	| 	< CANMOVE: "canMove" >
	| 	< NOT: "not" >
	|	< PICK:  "pick" > // For isValid condition
}


/* Cardinal directions */
TOKEN :
{
	 	< NORTH: "north" >
	| 	< SOUTH: "south" >
	| 	< EAST: "east" >
	| 	< WEST: "west" >
}


/* Directions */
TOKEN :
{
		< AROUND: "around" >
	| 	< RIGHT: "right" >
	| 	< LEFT: "left" >
	| 	< FRONT: "front" >
	| 	< BACK: "back" >
}


/* Keywords */
TOKEN :
{
		< PROG: "PROG" >
	|	< GORP: "GORP" >
	|	< VAR: "VAR" >
	|	< PROC: "PROC" >
	|	< CORP: "CORP" >
}


/* Name */
TOKEN :
{
		< NAME: <LETTER>(["a"-"z","A"-"Z","0"-"9"])* >
	|  	< #LETTER: ["a"-"z","A"-"Z"] >
}

/* Number */
TOKEN :
{
		< NUM: (<DIGIT>)+ >
	|  	< #DIGIT: ["0"-"9"] >
}


	boolean command(Console sistema):
	{
	}
	{
		< PROG > [varDecl()] (procDef())* instrBlock() < GORP > {
		    try {
	    		Thread.sleep(900);
	    	} catch (InterruptedException e) {
	    		System.err.format("IOException: %s%n", e);
	    	}
			sistema.printOutput(salida);
			return true;
		}
    	| <EOF> {return false;}
	}


	String varDecl():
	{
		String name;
	}
	{
		((< VAR > name=name()) {
			this.declaredVars.add(name);
		} ( LOOKAHEAD(2) "," (name=name()) {
			if (this.declaredVars.contains(name)) {
				throw new Error("Repeated variable name: "+name+" in variable declaration");
			} else {
				this.declaredVars.add(name);
			}
		} )* ";" ) {
			salida="Variable declaration";
		}
	}


	void procDef():
	{
		String procName;
		ArrayList<String> localVars = new ArrayList<String>();;
	}
	{
		< PROC > procName=name() "(" [localVars=params()] ")" instrBlock() < CORP > {
			/*TODO : Lógica Java definición de procedimientos*/
			salida="Procedure definition";
		}
	}


	ArrayList<String> params():
	{
		ArrayList<String> localVars = new ArrayList<String>();
		String name;
	}
	{
		((name=name()) {
			localVars.add(name);
		} ( LOOKAHEAD(2) "," (name=name()) {
			if (localVars.contains(name)) {
				throw new Error("Repeated parameter name: "+name);
			} else {
				localVars.add(name);
			}
		} )*) { return localVars; }
	}


	void instrBlock():
	{
	}
	{
		"{" instr() ( LOOKAHEAD(2) ";" instr())* "}"
	}


	void instr():
	{
	}
	{
		cmd()
	|	ctrlStruct()
	//|	procCall()
	}


	void cmd():
	{
		String name;
		Integer n, m;
	}
	{
		((name=name() ":=" n=num()) {
			if (declaredVars.contains(name)) {
				vars.put(name, n);
			} else {
				throw new Error("Tried to assign to undeclared variable "+name);
			}
			salida = "Command: Variable assignment";
		})
	|	(< STEP >  "(" n=num() ")" {world.moveForward(n, false); salida = "Command: Move steps forward ";})
	|	(< JUMP >  "(" n=num() ")" {world.moveForward(n, true); salida = "Command: Jump steps forward ";})
	|	(< JUMPTO >  "(" n=num() "," m=num()")" {world.setPostion(n,m); salida = "Command: Jump to position ";})
	|	(< VEER >  "(" veer() ")")
	|	(< LOOK >  "(" look() ")")
	|	(< DROP >  "(" n=num() ")" {world.putChips(n); salida = "Command: Drop chips from its position ";})
	|	(< GRAB >  "(" n=num() ")" {world.grabBalloons(n); salida = "Command: Grab balloons from its position ";})
	|	(< GET >  "(" n=num() ")" {world.pickChips(n); salida = "Command: Get chips from its position ";})
	|	(< FREE >  "(" n=num() ")" {world.putBalloons(n); salida = "Command: Put balloons from its position ";})
	|	(< POP >  "(" n=num() ")" {world.popBalloons(n); salida = "Command: Pop balloons from its position ";})
	|	(< DMOVE >  "(" dMove() ")")
	|	(< OMOVE >  "(" oMove() ")")
	}


	void ctrlStruct():
	{
	}
	{
		ifFi()
	|	whileDoOd()
	|	repeatTimes()
	}


	void ifFi():
	{
		boolean bool;
	}
	{
		(< IF > "(" bool=condition() ")" instrBlockTrue(bool) [< ELSE > instrBlockFalse(bool)] < FI >) {
			salida="'if' conditional control structure";
			}
	}


JAVACODE
	private void instrBlockTrue(boolean bool) {
		if (bool) {
			instrBlock();
		}
	}


JAVACODE
	void instrBlockFalse(boolean bool) {
		if (!bool) {
			instrBlock();
		}
	}


	void whileDoOd():
	{
		boolean bool;
	}
	{
		< WHILE > "(" bool=condition() ")" < DO > /*instrBlockWhile(bool)*/ < OD > {
			/*TODO : Lógica Java while. Implementar instrBlockWhile*/
			salida="'while' loop control structure";
			}
	}


	void repeatTimes():
	{
		Integer n;
	}
	{
		( < REPEATTIMES > n=num() ) {
			for (int i=0; i<n; i++) {
				instrBlock();
			}
		} ( < PER > ) {
			salida="'repeatTimes' loop control structure";
		}
	}


	boolean condition():
	{
		boolean bool;
	}
	{
		(< ISFACING >  "(" bool=isFacing() ")"
	|	< ISVALID >  "(" bool=isValid() ")"
	|	< CANMOVE >  "(" bool=canMove() ")"
	|	< NOT >  "(" bool=not() ")") {return bool;}
	}


//	void procCall():
//	{
//	}
//	{
//		// TODO
//	}


	void veer() :
	{
	}
	{
		(< RIGHT > {world.turnRight(); salida = "Command: Veer right ";})
	|	(< AROUND > {world.turnRight(); world.turnRight(); salida = "Command: Veer around ";})
	|	(< LEFT > {world.turnRight(); world.turnRight(); world.turnRight(); salida = "Command: Veer left ";})
	}


	void look() :
	{
	}
	{
		(< NORTH > {
			if (world.facingWest()) {
				world.turnRight();
			} else if (world.facingSouth()) {
				world.turnRight(); world.turnRight();
			} else if (world.facingEast()) {
				world.turnRight(); world.turnRight(); world.turnRight();
			}
			salida = "Command: Look north ";
		})
	|	(< SOUTH > {
			if (world.facingEast()) {
				world.turnRight();
			} else if (world.facingNorth()) {
				world.turnRight(); world.turnRight();
			} else if (world.facingWest()) {
				world.turnRight(); world.turnRight(); world.turnRight();
			}
			salida = "Command: Look south ";
		})
	|	(< EAST > {
			if (world.facingNorth()) {
				world.turnRight();
			} else if (world.facingWest()) {
				world.turnRight(); world.turnRight();
			} else if (world.facingSouth()) {
				world.turnRight(); world.turnRight(); world.turnRight();
			}
			salida = "Command: Look east ";
		})
	|	(< WEST > {
			if (world.facingSouth()) {
				world.turnRight();
			} else if (world.facingEast()) {
				world.turnRight(); world.turnRight();
			} else if (world.facingNorth()) {
				world.turnRight(); world.turnRight(); world.turnRight();
			}
			salida = "Command: Look west ";
		})
	}


	void dMove() :
	{
		Integer n;
	}
	{ n = num() ","
		(( < FRONT > {
			world.moveForward(n, false);
			salida = "Command: Move to the front, face original direction ";
		})
	|	( < RIGHT > {
			world.turnRight();
			world.moveForward(n, false);
			world.turnRight(); world.turnRight(); world.turnRight();
			salida = "Command: Move to the right, face original direction ";
		})
	|	( < BACK > {
			world.turnRight(); world.turnRight();
			world.moveForward(n, false);
			world.turnRight(); world.turnRight();
			salida = "Command: Move to the back, face original direction ";
		})
	|	( < LEFT > {
			world.turnRight(); world.turnRight(); world.turnRight();
			world.moveForward(n, false);
			world.turnRight();
			salida = "Command: Move to the left, face original direction ";
		}))
	}


	void oMove() :
	{
		Integer n;
	}
	{ n = num() "," 
		((< NORTH > {
			if (world.facingWest()) {
				world.turnRight();
			} else if (world.facingSouth()) {
				world.turnRight(); world.turnRight();
			} else if (world.facingEast()) {
				world.turnRight(); world.turnRight(); world.turnRight();
			}
			world.moveForward(n, false);
			salida = "Command: Face north, move steps";
		})
	|	(< SOUTH > {
			if (world.facingEast()) {
				world.turnRight();
			} else if (world.facingNorth()) {
				world.turnRight(); world.turnRight();
			} else if (world.facingWest()) {
				world.turnRight(); world.turnRight(); world.turnRight();
			}
			world.moveForward(n, false);
			salida = "Command: Face south, move steps";
		})
	|	(< EAST > {
			if (world.facingNorth()) {
				world.turnRight();
			} else if (world.facingWest()) {
				world.turnRight(); world.turnRight();
			} else if (world.facingSouth()) {
				world.turnRight(); world.turnRight(); world.turnRight();
			}
			world.moveForward(n, false);
			salida = "Command: Face east, move steps";
		})
	|	(< WEST > {
			if (world.facingSouth()) {
				world.turnRight();
			} else if (world.facingEast()) {
				world.turnRight(); world.turnRight();
			} else if (world.facingNorth()) {
				world.turnRight(); world.turnRight(); world.turnRight();
			}
			world.moveForward(n, false);
			salida = "Command: Face west, move steps";
		}))
	}


	boolean isFacing():
	{
		boolean bool;
	}
	{
		((< NORTH > {
			bool=world.facingNorth();})
	|	(< SOUTH > {
			bool=world.facingSouth();})
	|	(< EAST > {
			bool=world.facingEast();})
	|	(< WEST > {
			bool=world.facingWest();})) { return bool; }
	}


	boolean isValid():
	{
		Integer n;
		boolean bool = true;
		int pasos;
		int posX;
		int posY;
		boolean outOfBounds;
	}
	{ // TODO: Que n pueda ser tambien var o param
		((< STEP > ","  n=num() {
			pasos = n;
			posX = (int) world.getPosition().getX();
			posY = (int) world.getPosition().getY();
			/* Check if final position is on board */
			outOfBounds = false;
			if(world.facingNorth()) {
				if (posY-pasos < 1) { outOfBounds = true; }
			}	
			else if(world.facingSouth()) {
				if (posY+pasos > 8) { outOfBounds = true; }
			}
			else if(world.facingEast()) { 
				if (posX+pasos > 8) { outOfBounds = true; }
			}
			else if(world.facingWest()) { 
				if (posX-pasos < 1) { outOfBounds = true; }
			}
			
			if (outOfBounds) {
				bool = false;
			} else {
				/*Check if path is blocked*/
				if(world.facingNorth())
					bool = !world.blockedInRange(posX, posY, posY-pasos, 0);
				else if(world.facingSouth()) 
					bool = !world.blockedInRange(posX, posY, posY+pasos, 1);
				else if(world.facingEast())
					bool = !world.blockedInRange(posX, posY, posX+pasos, 2);
				else if(world.facingWest())
					bool = !world.blockedInRange(posX, posY, posX-pasos, 3);
			}
		})
	|	(< JUMP > ","  n=num() {
			pasos = n;
			posX = (int) world.getPosition().getX();
			posY = (int) world.getPosition().getY();
			/* Check if final position is on board */
			outOfBounds = false;
			if(world.facingNorth()) {
				if (posY-pasos < 1) { outOfBounds = true; }
			}	
			else if(world.facingSouth()) {
				if (posY+pasos > 8) { outOfBounds = true; }
			}
			else if(world.facingEast()) { 
				if (posX+pasos > 8) { outOfBounds = true; }
			}
			else if(world.facingWest()) { 
				if (posX-pasos < 1) { outOfBounds = true; }
			}
			
			if (outOfBounds) {
				bool = false;
			} else {
				/*Check if final position is blocked*/
				if(world.facingNorth())
					bool = !world.isBlocked(new Point(posX, posY-pasos));
				else if(world.facingSouth()) 
					bool = !world.isBlocked(new Point(posX, posY+pasos));
				else if(world.facingEast())
					bool = !world.isBlocked(new Point(posX, posX+pasos));
				else if(world.facingWest())
					bool = !world.isBlocked(new Point(posX, posX-pasos));
			}
		})
	|	(< GRAB > ","  n=num() {
			if ((n < 0) || (world.countBalloons(world.getPosition()) < n)) {
				bool = false;
			}
		})
	|	(< POP > ","  n=num() {
			if ((n < 0) || (world.countBalloons(world.getPosition()) < n)) {
				bool = false;
			}		})
	|	(< PICK > ","  n=num() { /* Equivalent to 'grab' */
			if ((n < 0) || (world.countBalloons(world.getPosition()) < n)) {
				bool = false;
			}
		}) 
	|	(< FREE > ","  n=num() {
			if ((n < 0) || (world.getMyBalloons()< n)) {
				bool = false;
			}
		})
	|	(< DROP > ","  n=num() {
			if ((n < 0) || (n > world.freeSpacesForChips()) || (world.getMyChips()< n)) {
				bool = false;
			}
		})) { return bool; }
	}


	boolean canMove():
	{
		Integer n;
		boolean bool = true;
		int pasos;
		int posX;
		int posY;
	}
	{  // TODO: Que n pueda ser tambien var o param
		((< NORTH > ","  n=num() {
			pasos = n;
			posX = (int) world.getPosition().getX();
			posY = (int) world.getPosition().getY();
			bool = !world.blockedInRange(posX, posY, posY-pasos, 0);
		})
	|	(< SOUTH > ","  n=num() {
			pasos = n;
			posX = (int) world.getPosition().getX();
			posY = (int) world.getPosition().getY();
			bool = !world.blockedInRange(posX, posY, posY+pasos, 1);
		})
	|	(< EAST > ","  n=num() {
			pasos = n;
			posX = (int) world.getPosition().getX();
			posY = (int) world.getPosition().getY();
			bool = !world.blockedInRange(posX, posY, posX+pasos, 2);
		})
	|	(< WEST > ","  n=num() {
			pasos = n;
			posX = (int) world.getPosition().getX();
			posY = (int) world.getPosition().getY();
			bool = !world.blockedInRange(posX, posY, posX-pasos, 3);
		})) { return bool; }
	}


	boolean not():
	{
		boolean bool;
	}
	{
		bool=condition() {return !bool;}
	}



	String name():
	{
	}
	{
		< NAME > { return token.image; }
	}


	/**
	 * Unsigned decimal number
	 * @return the corresponding value of the string
	 * @error  corresponding value is too large
	 */

	Integer num() throws Error:
	{
		int total_;
		Integer total;
	}
	{
		<NUM>
		{
			try 
			{
				total_ = Integer.parseInt(token.image);
				total = Integer.valueOf(total_);
			} 
			catch (NumberFormatException ee) 
			{
				throw new Error("Number out of bounds: "+token.image+" !!");
			}
			return total;
		}
	}

