/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOVE = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int STEP = 12;
  /** RegularExpression Id. */
  int JUMP = 13;
  /** RegularExpression Id. */
  int JUMPTO = 14;
  /** RegularExpression Id. */
  int VEER = 15;
  /** RegularExpression Id. */
  int LOOK = 16;
  /** RegularExpression Id. */
  int DROP = 17;
  /** RegularExpression Id. */
  int GRAB = 18;
  /** RegularExpression Id. */
  int GET = 19;
  /** RegularExpression Id. */
  int FREE = 20;
  /** RegularExpression Id. */
  int BALLOONS = 21;
  /** RegularExpression Id. */
  int CHIPS = 22;
  /** RegularExpression Id. */
  int NORTH = 23;
  /** RegularExpression Id. */
  int SOUTH = 24;
  /** RegularExpression Id. */
  int EAST = 25;
  /** RegularExpression Id. */
  int WEST = 26;
  /** RegularExpression Id. */
  int NUM = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"move\"",
    "\"right\"",
    "\"Put\"",
    "\"Pick\"",
    "\"pop\"",
    "\"Go\"",
    "\"Hop\"",
    "\"step\"",
    "\"jump\"",
    "\"jumpTo\"",
    "\"veer\"",
    "\"look\"",
    "\"drop\"",
    "\"grab\"",
    "\"get\"",
    "\"free\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "<NUM>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
  };

}
