/* Generated By:JavaCC: Do not edit this line. Robot.java */
package uniandes.lym.robot.control;

import uniandes.lym.robot.kernel.*;
import uniandes.lym.robot.view.Console;

import java.awt.Point;
import java.io.*;
import java.util.*;

@SuppressWarnings("serial")
public class Robot implements RobotConstants {
        private RobotWorldDec world;


        void setWorld(RobotWorld w) {
                world = (RobotWorldDec) w;
        }


        private String salida = new String();

        private ArrayList<String> declaredVars = new ArrayList<String>();
        private Hashtable<String, Integer> vars = new Hashtable<String, Integer>();
        private ArrayList<String> procsNames = new ArrayList<String>();
        private Hashtable<String, ArrayList<String>> procsParams = new Hashtable<String, ArrayList<String>>();
        private Hashtable<String, ArrayList<String>> procsInstrs = new Hashtable<String, ArrayList<String>>();

  final public boolean command(Console sistema) throws ParseException {
                salida = "";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PROG:
      jj_consume_token(PROG);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VAR:
        varDecl();
        break;
      default:
        jj_la1[0] = jj_gen;
        ;
      }
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PROC:
          ;
          break;
        default:
          jj_la1[1] = jj_gen;
          break label_1;
        }
        procDef();
      }
      instrBlock();
      jj_consume_token(GORP);
                    try {
                        Thread.sleep(900);
                } catch (InterruptedException e) {
                        System.err.format("IOException: %s%n", e);
                }
                        sistema.printOutput(salida);
                        {if (true) return true;}
      break;
    case 0:
      jj_consume_token(0);
                 {if (true) return false;}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public void varDecl() throws ParseException {
                String name;
    jj_consume_token(VAR);
    name = name();
                        this.declaredVars.add(name);
    label_2:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_2;
      }
      jj_consume_token(48);
      name = name();
                        if (this.declaredVars.contains(name)) {
                                {if (true) throw new Error("Repeated variable name: "+name+ " in variable declaration");}
                        } else {
                                this.declaredVars.add(name);
                        }
    }
    jj_consume_token(49);
                        this.salida = this.salida + "\u005cnVariable declaration";
  }

  final public void procDef() throws ParseException {
                String name;
                ArrayList<String> localVars = new ArrayList<String>();
                ArrayList<String> instructions = new ArrayList<String>();
    jj_consume_token(PROC);
    name = name();
    jj_consume_token(50);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      localVars = params();
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    jj_consume_token(51);
                        if (procsNames.contains(name)) {
                                {if (true) throw new Error ("Procedure with name "+name+" has already been declared");}
                        }
                        procsNames.add(name);
                        procsParams.put(name, localVars);
    procInstrBlock();
    jj_consume_token(CORP);
                  this.salida = this.salida + "\u005cnProcedure definition";
  }

  final public ArrayList<String> params() throws ParseException {
                ArrayList<String> localVars = new ArrayList<String>();
                String name;
    name = name();
                        localVars.add(name);
    label_3:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_3;
      }
      jj_consume_token(48);
      name = name();
                        if (localVars.contains(name)) {
                                {if (true) throw new Error("Repeated parameter name: "+name);}
                        } else {
                                localVars.add(name);
                        }
    }
                        {if (true) return localVars;}
    throw new Error("Missing return statement in function");
  }

  final public void instrBlock() throws ParseException {
    jj_consume_token(52);
    instr();
    label_4:
    while (true) {
      if (jj_2_3(2)) {
        ;
      } else {
        break label_4;
      }
      jj_consume_token(49);
      instr();
    }
    jj_consume_token(53);
  }

  final public void instr() throws ParseException {
    if (jj_2_4(2)) {
      cmd();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case REPEATTIMES:
        ctrlStruct();
        break;
      case NAME:
        procCall();
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void cmd() throws ParseException {
                String name;
                Integer n, m;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      name = name();
      jj_consume_token(54);
      n = num();
                        if (declaredVars.contains(name)) {
                                vars.put(name, n);
                        } else {
                                {if (true) throw new Error("Tried to assign to undeclared variable "+name);}
                        }
                        this.salida = this.salida + "\u005cnCommand: Variable assignment";
      break;
    case STEP:
      jj_consume_token(STEP);
      jj_consume_token(50);
      n = numVar();
      jj_consume_token(51);
                                                 world.moveForward(n, false); this.salida = this.salida + "\u005cnCommand: Move steps forward ";
      break;
    case JUMP:
      jj_consume_token(JUMP);
      jj_consume_token(50);
      n = numVar();
      jj_consume_token(51);
                                                  world.moveForward(n, true); this.salida = this.salida + "\u005cnCommand: Jump steps forward ";
      break;
    case JUMPTO:
      jj_consume_token(JUMPTO);
      jj_consume_token(50);
      n = numVar();
      jj_consume_token(48);
      m = numVar();
      jj_consume_token(51);
                                                                    world.setPostion(n,m); this.salida = this.salida + "\u005cnCommand: Jump to position ";
      break;
    case VEER:
      jj_consume_token(VEER);
      jj_consume_token(50);
      veer();
      jj_consume_token(51);
      break;
    case LOOK:
      jj_consume_token(LOOK);
      jj_consume_token(50);
      look();
      jj_consume_token(51);
      break;
    case DROP:
      jj_consume_token(DROP);
      jj_consume_token(50);
      n = numVar();
      jj_consume_token(51);
                                                  world.putChips(n); this.salida = this.salida + "\u005cnCommand: Drop chips from its position ";
      break;
    case GRAB:
      jj_consume_token(GRAB);
      jj_consume_token(50);
      n = numVar();
      jj_consume_token(51);
                                                  world.grabBalloons(n); this.salida = this.salida + "\u005cnCommand: Grab balloons from its position ";
      break;
    case GET:
      jj_consume_token(GET);
      jj_consume_token(50);
      n = numVar();
      jj_consume_token(51);
                                                 world.pickChips(n); this.salida = this.salida + "\u005cnCommand: Get chips from its position ";
      break;
    case FREE:
      jj_consume_token(FREE);
      jj_consume_token(50);
      n = numVar();
      jj_consume_token(51);
                                                  world.putBalloons(n); this.salida = this.salida + "\u005cnCommand: Put balloons from its position ";
      break;
    case POP:
      jj_consume_token(POP);
      jj_consume_token(50);
      n = numVar();
      jj_consume_token(51);
                                                 world.popBalloons(n); this.salida = this.salida + "\u005cnCommand: Pop balloons from its position ";
      break;
    case DMOVE:
      jj_consume_token(DMOVE);
      jj_consume_token(50);
      dMove();
      jj_consume_token(51);
      break;
    case OMOVE:
      jj_consume_token(OMOVE);
      jj_consume_token(50);
      oMove();
      jj_consume_token(51);
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void ctrlStruct() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
      ifFi();
      break;
    case WHILE:
      whileDoOd();
      break;
    case REPEATTIMES:
      repeatTimes();
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void ifFi() throws ParseException {
                boolean bool;
    jj_consume_token(IF);
    jj_consume_token(50);
    bool = condition();
    jj_consume_token(51);
    jj_consume_token(52);
    instrIf(bool);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 49:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_5;
      }
      jj_consume_token(49);
      instrIf(bool);
    }
    jj_consume_token(53);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      jj_consume_token(52);
      instrIf(!bool);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 49:
          ;
          break;
        default:
          jj_la1[8] = jj_gen;
          break label_6;
        }
        jj_consume_token(49);
        instrIf(!bool);
      }
      jj_consume_token(53);
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(FI);
                this.salida = this.salida + "\u005cn'if' conditional control structure";
  }

  private void instrIf(boolean bool) throws ParseException {
                if (bool) {
                        instr();
                } else {
                        checkSintaxInstr();
                }
  }

  final public void whileDoOd() throws ParseException {
                boolean bool;
    jj_consume_token(WHILE);
    jj_consume_token(50);
    bool = condition();
    jj_consume_token(51);
    jj_consume_token(DO);
    whileInstrBlock(bool);
    jj_consume_token(OD);
                        this.salida = this.salida + "\u005cn'while' loop control structure";
  }

  final public void repeatTimes() throws ParseException {
                Integer n;
    jj_consume_token(REPEATTIMES);
    n = numVar();
    repeatInstrBlock(n);
    jj_consume_token(PER);
                        this.salida = this.salida + "\u005cn'repeatTimes' loop control structure";
  }

  final public boolean condition() throws ParseException {
                boolean bool;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ISFACING:
      jj_consume_token(ISFACING);
      jj_consume_token(50);
      bool = isFacing();
      jj_consume_token(51);
      break;
    case ISVALID:
      jj_consume_token(ISVALID);
      jj_consume_token(50);
      bool = isValid();
      jj_consume_token(51);
      break;
    case CANMOVE:
      jj_consume_token(CANMOVE);
      jj_consume_token(50);
      bool = canMove();
      jj_consume_token(51);
      break;
    case NOT:
      jj_consume_token(NOT);
      jj_consume_token(50);
      bool = not();
      jj_consume_token(51);
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                              {if (true) return bool;}
    throw new Error("Missing return statement in function");
  }

  final public void procCall() throws ParseException {
                String name;
                ArrayList<String> rParams = new ArrayList<String>();
    name = name();
    jj_consume_token(50);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      rParams = params();
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(51);
                        if (!procsNames.contains(name)) {
                                {if (true) throw new Error("Tried to call undeclared procedure");}
                        }
                        if (rParams.size() != procsParams.get(name).size()) {
                                {if (true) throw new Error("Incorrect number of parameters for "+name+" procedure");}
                        }
                        // TODO: Ejecutar el proc llamado

  }

  final public void veer() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RIGHT:
      jj_consume_token(RIGHT);
                            world.turnRight(); this.salida = this.salida + "\u005cnCommand: Veer right ";
      break;
    case AROUND:
      jj_consume_token(AROUND);
                             world.turnRight(); world.turnRight(); this.salida = this.salida + "\u005cnCommand: Veer around ";
      break;
    case LEFT:
      jj_consume_token(LEFT);
                           world.turnRight(); world.turnRight(); world.turnRight(); this.salida = this.salida + "\u005cnCommand: Veer left ";
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void look() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NORTH:
      jj_consume_token(NORTH);
                        if (world.facingWest()) {
                                world.turnRight();
                        } else if (world.facingSouth()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingEast()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        this.salida = this.salida + "\u005cnCommand: Look north ";
      break;
    case SOUTH:
      jj_consume_token(SOUTH);
                        if (world.facingEast()) {
                                world.turnRight();
                        } else if (world.facingNorth()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingWest()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        this.salida = this.salida + "\u005cnCommand: Look south ";
      break;
    case EAST:
      jj_consume_token(EAST);
                        if (world.facingNorth()) {
                                world.turnRight();
                        } else if (world.facingWest()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingSouth()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        this.salida = this.salida + "\u005cnCommand: Look east ";
      break;
    case WEST:
      jj_consume_token(WEST);
                        if (world.facingSouth()) {
                                world.turnRight();
                        } else if (world.facingEast()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingNorth()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        this.salida = this.salida + "\u005cnCommand: Look west ";
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void dMove() throws ParseException {
                Integer n;
    n = numVar();
    jj_consume_token(48);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FRONT:
      jj_consume_token(FRONT);
                        world.moveForward(n, false);
                        this.salida = this.salida + "\u005cnCommand: Move to the front, face original direction ";
      break;
    case RIGHT:
      jj_consume_token(RIGHT);
                        world.turnRight();
                        world.moveForward(n, false);
                        world.turnRight(); world.turnRight(); world.turnRight();
                        this.salida = this.salida + "\u005cnCommand: Move to the right, face original direction ";
      break;
    case BACK:
      jj_consume_token(BACK);
                        world.turnRight(); world.turnRight();
                        world.moveForward(n, false);
                        world.turnRight(); world.turnRight();
                        this.salida = this.salida + "\u005cnCommand: Move to the back, face original direction ";
      break;
    case LEFT:
      jj_consume_token(LEFT);
                        world.turnRight(); world.turnRight(); world.turnRight();
                        world.moveForward(n, false);
                        world.turnRight();
                        this.salida = this.salida + "\u005cnCommand: Move to the left, face original direction ";
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void oMove() throws ParseException {
                Integer n;
    n = numVar();
    jj_consume_token(48);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NORTH:
      jj_consume_token(NORTH);
                        if (world.facingWest()) {
                                world.turnRight();
                        } else if (world.facingSouth()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingEast()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        world.moveForward(n, false);
                        this.salida = this.salida + "\u005cnCommand: Face north, move steps";
      break;
    case SOUTH:
      jj_consume_token(SOUTH);
                        if (world.facingEast()) {
                                world.turnRight();
                        } else if (world.facingNorth()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingWest()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        world.moveForward(n, false);
                        this.salida = this.salida + "\u005cnCommand: Face south, move steps";
      break;
    case EAST:
      jj_consume_token(EAST);
                        if (world.facingNorth()) {
                                world.turnRight();
                        } else if (world.facingWest()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingSouth()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        world.moveForward(n, false);
                        this.salida = this.salida + "\u005cnCommand: Face east, move steps";
      break;
    case WEST:
      jj_consume_token(WEST);
                        if (world.facingSouth()) {
                                world.turnRight();
                        } else if (world.facingEast()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingNorth()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        world.moveForward(n, false);
                        this.salida = this.salida + "\u005cnCommand: Face west, move steps";
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public boolean isFacing() throws ParseException {
                boolean bool;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NORTH:
      jj_consume_token(NORTH);
                        bool=world.facingNorth();
      break;
    case SOUTH:
      jj_consume_token(SOUTH);
                        bool=world.facingSouth();
      break;
    case EAST:
      jj_consume_token(EAST);
                        bool=world.facingEast();
      break;
    case WEST:
      jj_consume_token(WEST);
                        bool=world.facingWest();
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                      {if (true) return bool;}
    throw new Error("Missing return statement in function");
  }

  final public boolean isValid() throws ParseException {
                Integer n;
                boolean bool = true;
                int pasos;
                int posX;
                int posY;
                boolean outOfBounds;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STEP:
      jj_consume_token(STEP);
      jj_consume_token(48);
      n = numVar();
                                                // p
                        pasos = n;
                        posX = (int) world.getPosition().getX();
                        posY = (int) world.getPosition().getY();
                        /* Check if final position is on board */
                        outOfBounds = false;
                        if(world.facingNorth()) {
                                if (posY-pasos < 1) { outOfBounds = true; }
                        }
                        else if(world.facingSouth()) {
                                if (posY+pasos > 8) { outOfBounds = true; }
                        }
                        else if(world.facingEast()) {
                                if (posX+pasos > 8) { outOfBounds = true; }
                        }
                        else if(world.facingWest()) {
                                if (posX-pasos < 1) { outOfBounds = true; }
                        }

                        if (outOfBounds) {
                                bool = false;
                        } else {
                                /*Check if path is blocked*/
                                if(world.facingNorth())
                                        bool = !world.blockedInRange(posX, posY, posY-pasos, 0);
                                else if(world.facingSouth())
                                        bool = !world.blockedInRange(posX, posY, posY+pasos, 1);
                                else if(world.facingEast())
                                        bool = !world.blockedInRange(posX, posY, posX+pasos, 2);
                                else if(world.facingWest())
                                        bool = !world.blockedInRange(posX, posY, posX-pasos, 3);
                        }
      break;
    case JUMP:
      jj_consume_token(JUMP);
      jj_consume_token(48);
      n = numVar();
                        pasos = n;
                        posX = (int) world.getPosition().getX();
                        posY = (int) world.getPosition().getY();
                        /* Check if final position is on board */
                        outOfBounds = false;
                        if(world.facingNorth()) {
                                if (posY-pasos < 1) { outOfBounds = true; }
                        }
                        else if(world.facingSouth()) {
                                if (posY+pasos > 8) { outOfBounds = true; }
                        }
                        else if(world.facingEast()) {
                                if (posX+pasos > 8) { outOfBounds = true; }
                        }
                        else if(world.facingWest()) {
                                if (posX-pasos < 1) { outOfBounds = true; }
                        }

                        if (outOfBounds) {
                                bool = false;
                        } else {
                                /*Check if final position is blocked*/
                                if(world.facingNorth())
                                        bool = !world.isBlocked(new Point(posX, posY-pasos));
                                else if(world.facingSouth())
                                        bool = !world.isBlocked(new Point(posX, posY+pasos));
                                else if(world.facingEast())
                                        bool = !world.isBlocked(new Point(posX, posX+pasos));
                                else if(world.facingWest())
                                        bool = !world.isBlocked(new Point(posX, posX-pasos));
                        }
      break;
    case GRAB:
      jj_consume_token(GRAB);
      jj_consume_token(48);
      n = numVar();
                        if ((n < 0) || (world.countBalloons(world.getPosition()) < n)) {
                                bool = false;
                        }
      break;
    case POP:
      jj_consume_token(POP);
      jj_consume_token(48);
      n = numVar();
                        if ((n < 0) || (world.countBalloons(world.getPosition()) < n)) {
                                bool = false;
                        }
      break;
    case PICK:
      jj_consume_token(PICK);
      jj_consume_token(48);
      n = numVar();
                                               /* Equivalent to 'grab' */
                        if ((n < 0) || (world.countBalloons(world.getPosition()) < n)) {
                                bool = false;
                        }
      break;
    case FREE:
      jj_consume_token(FREE);
      jj_consume_token(48);
      n = numVar();
                        if ((n < 0) || (world.getMyBalloons()< n)) {
                                bool = false;
                        }
      break;
    case DROP:
      jj_consume_token(DROP);
      jj_consume_token(48);
      n = numVar();
                        if ((n < 0) || (n > world.freeSpacesForChips()) || (world.getMyChips()< n)) {
                                bool = false;
                        }
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                      {if (true) return bool;}
    throw new Error("Missing return statement in function");
  }

  final public boolean canMove() throws ParseException {
                Integer n;
                boolean bool = true;
                int pasos;
                int posX;
                int posY;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NORTH:
      jj_consume_token(NORTH);
      jj_consume_token(48);
      n = numVar();
                                              // p
                        pasos = n;
                        posX = (int) world.getPosition().getX();
                        posY = (int) world.getPosition().getY();
                        bool = !world.blockedInRange(posX, posY, posY-pasos, 0);
      break;
    case SOUTH:
      jj_consume_token(SOUTH);
      jj_consume_token(48);
      n = numVar();
                        pasos = n;
                        posX = (int) world.getPosition().getX();
                        posY = (int) world.getPosition().getY();
                        bool = !world.blockedInRange(posX, posY, posY+pasos, 1);
      break;
    case EAST:
      jj_consume_token(EAST);
      jj_consume_token(48);
      n = numVar();
                        pasos = n;
                        posX = (int) world.getPosition().getX();
                        posY = (int) world.getPosition().getY();
                        bool = !world.blockedInRange(posX, posY, posX+pasos, 2);
      break;
    case WEST:
      jj_consume_token(WEST);
      jj_consume_token(48);
      n = numVar();
                        pasos = n;
                        posX = (int) world.getPosition().getX();
                        posY = (int) world.getPosition().getY();
                        bool = !world.blockedInRange(posX, posY, posX-pasos, 3);
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                      {if (true) return bool;}
    throw new Error("Missing return statement in function");
  }

  final public boolean not() throws ParseException {
                boolean bool;
    bool = condition();
                                  {if (true) return !bool;}
    throw new Error("Missing return statement in function");
  }

  final public void checkSintaxInstrBlock() throws ParseException {
    jj_consume_token(52);
    checkSintaxInstr();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 49:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_7;
      }
      jj_consume_token(49);
      checkSintaxInstr();
    }
    jj_consume_token(53);
  }

  final public void procInstrBlock() throws ParseException {
    jj_consume_token(52);
    checkSintaxInstr();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 49:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_8;
      }
      jj_consume_token(49);
      checkSintaxInstr();
    }
    jj_consume_token(53);
  }

  final public void repeatInstrBlock(Integer n) throws ParseException {
                ArrayList<String> instrs = new ArrayList<String>();
                ArrayList<String> instr = new ArrayList<String>();
    jj_consume_token(52);
    instr = saveInstr();
                                         instrs.addAll(instr);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 49:
        ;
        break;
      default:
        jj_la1[21] = jj_gen;
        break label_9;
      }
      jj_consume_token(49);
      instr = saveInstr();
                                                                                           instrs.addAll(instr);
    }
    jj_consume_token(53);
                        for(Integer i = 0; i < n; i++) {
                                manuallyExecuteInstrs(instrs);
                        }
  }

  final public void whileInstrBlock(boolean bool) throws ParseException {
    jj_consume_token(52);
    instrWhile(bool);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 49:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_10;
      }
      jj_consume_token(49);
      instrWhile(bool);
    }
    jj_consume_token(53);
  }

  private void instrWhile(boolean bool) throws ParseException {
                if (bool) {
                        instr();
                } else {
                        checkSintaxInstr();
                }
  }

  private void manuallyExecuteInstrs(ArrayList<String> oInstrs) throws ParseException {
                ArrayList<String> instrs = (ArrayList<String>) oInstrs.clone();
                Integer n, m;
                String dir, insName;
                for (Integer i = 0; i < instrs.size(); i++) {
                        insName = instrs.get(i).trim();
                        if (insName.equals("step")) {
                                n = Integer.valueOf(instrs.get(i+1));
                                world.moveForward(n, false);
                                i++;
                                this.salida = this.salida + "\u005cnCommand: Move steps forward ";
                        } else if (insName.equals("jump")) {
                                n = Integer.valueOf(instrs.get(i+1));
                                world.moveForward(n, true);
                                i++;
                                this.salida = this.salida + "\u005cnCommand: Jump steps forward ";
                        } else if (insName.equals("drop")) {
                                n = Integer.valueOf(instrs.get(i+1));
                                world.putChips(n);
                                i++;
                                this.salida = this.salida + "\u005cnCommand: Drop chips from its position ";
                        } else if (insName.equals("grab")) {
                                n = Integer.valueOf(instrs.get(i+1));
                                world.grabBalloons(n);
                                i++;
                                this.salida = this.salida + "\u005cnCommand: Grab balloons from its position ";
                        } else if (insName.equals("get")) {
                                n = Integer.valueOf(instrs.get(i+1));
                                world.pickChips(n);
                                i++;
                                this.salida = this.salida + "\u005cnCommand: Get chips from its position ";
                        } else if (insName.equals("free")) {
                                n = Integer.valueOf(instrs.get(i+1));
                                world.putBalloons(n);
                                i++;
                                this.salida = this.salida + "\u005cnCommand: Put balloons from its position ";
                        } else if (insName.equals("pop")) {
                                n = Integer.valueOf(instrs.get(i+1));
                                world.popBalloons(n);
                                i++;
                                this.salida = this.salida + "\u005cnCommand: Pop balloons from its position ";
                        } else if (insName.equals("jumpTo")) {
                                n = Integer.valueOf(instrs.get(i+1));
                                m = Integer.valueOf(instrs.get(i+2));
                                world.setPostion(n, m);
                                i += 2;
                                this.salida = this.salida + "\u005cnCommand: Jump to position ";
                        } else if (insName.equals("veer")) {
                                dir = instrs.get(i+1);
                                manualVeer(dir);
                                i++;
                        } else if (insName.equals("look")) {
                                dir = instrs.get(i+1);
                                manualLook(dir);
                                i++;
                        } else if (insName.equals("Dmove")) {
                                n = Integer.valueOf(instrs.get(i+1));
                                dir = instrs.get(i+2);
                                manualDMove(n, dir);
                                i+=2;
                        } else if (insName.equals("Omove")) {
                                n = Integer.valueOf(instrs.get(i+1));
                                dir = instrs.get(i+2);
                                manualOMove(n, dir);
                                i+=2;
                        } else if (insName.equals("if")) {
                                ; // Skip the 'if', beca
                        } else if (this.declaredVars.contains(insName)) {
                                n = Integer.valueOf(instrs.get(i+1));
                                this.vars.put(insName, n);
                                this.salida = this.salida + "\u005cnCommand: Variable assignment";
                                i++;
                        }
                }
  }

  private void manualVeer(String dir) throws ParseException {
                if (dir.equals("right")) {
                        world.turnRight();
                        this.salida = this.salida + "\u005cnCommand: Veer right ";
                } else if (dir.equals("around")) {
                        world.turnRight();
                        world.turnRight();
                        this.salida = this.salida + "\u005cnCommand: Veer around ";
                } else if (dir.equals("left")) {
                        world.turnRight();
                        world.turnRight();
                        world.turnRight();
                        this.salida = this.salida + "\u005cnCommand: Veer left ";
                }
  }

  private void manualLook(String dir) throws ParseException {
                if (dir.equals("north")) {
                        if (world.facingWest()) {
                                world.turnRight();
                        } else if (world.facingSouth()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingEast()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        this.salida = this.salida + "\u005cnCommand: Look north ";
                } else if (dir.equals("south")) {
                        if (world.facingEast()) {
                                world.turnRight();
                        } else if (world.facingNorth()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingWest()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        this.salida = this.salida + "\u005cnCommand: Look south ";
                } else if (dir.equals("east")) {
                        if (world.facingNorth()) {
                                world.turnRight();
                        } else if (world.facingWest()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingSouth()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        this.salida = this.salida + "\u005cnCommand: Look east ";
                } else if (dir.equals("west")) {
                        if (world.facingSouth()) {
                                world.turnRight();
                        } else if (world.facingEast()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingNorth()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        this.salida = this.salida + "\u005cnCommand: Look west ";
                }
  }

  private void manualDMove(Integer n, String dir) throws ParseException {
                if (dir.equals("front")) {
                        world.moveForward(n, false);
                        this.salida = this.salida + "\u005cnCommand: Move to the front, face original direction ";
                } else if (dir.equals("right")) {
                        world.turnRight();
                        world.moveForward(n, false);
                        world.turnRight(); world.turnRight(); world.turnRight();
                        this.salida = this.salida + "\u005cnCommand: Move to the right, face original direction ";
                } else if (dir.equals("back")) {
                        world.turnRight(); world.turnRight();
                        world.moveForward(n, false);
                        world.turnRight(); world.turnRight();
                        this.salida = this.salida + "\u005cnCommand: Move to the back, face original direction ";
                } else if (dir.equals("left")) {
                        world.turnRight(); world.turnRight(); world.turnRight();
                        world.moveForward(n, false);
                        world.turnRight();
                        this.salida = this.salida + "\u005cnCommand: Move to the left, face original direction ";
                }
  }

  private void manualOMove(Integer n, String dir) throws ParseException {
                if (dir.equals("north")) {
                        if (world.facingWest()) {
                                world.turnRight();
                        } else if (world.facingSouth()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingEast()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        world.moveForward(n, false);
                        this.salida = this.salida + "\u005cnCommand: Face north, move steps";
                } else if (dir.equals("south")) {
                        if (world.facingEast()) {
                                world.turnRight();
                        } else if (world.facingNorth()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingWest()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        world.moveForward(n, false);
                        this.salida = this.salida + "\u005cnCommand: Face south, move steps";
                } else if (dir.equals("east")) {
                        if (world.facingNorth()) {
                                world.turnRight();
                        } else if (world.facingWest()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingSouth()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        world.moveForward(n, false);
                        this.salida = this.salida + "\u005cnCommand: Face east, move steps";
                } else if (dir.equals("west")) {
                        if (world.facingSouth()) {
                                world.turnRight();
                        } else if (world.facingEast()) {
                                world.turnRight(); world.turnRight();
                        } else if (world.facingNorth()) {
                                world.turnRight(); world.turnRight(); world.turnRight();
                        }
                        world.moveForward(n, false);
                        this.salida = this.salida + "\u005cnCommand: Face west, move steps";
                }
  }

  final public ArrayList<String> saveInstr() throws ParseException {
                ArrayList<String> instr = new ArrayList<String>();
    if (jj_2_5(2)) {
      instr = saveCmd();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case REPEATTIMES:
        instr = saveCtrlStruct();
        break;
      case NAME:
        instr = saveProcCall();
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                                          {if (true) return instr;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<String> saveCmd() throws ParseException {
                ArrayList<String> cmd = new ArrayList<String>();
                ArrayList<String> l = new ArrayList<String>();
                int n, m;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      jj_consume_token(NAME);
                              cmd.add(token.image);
      jj_consume_token(54);
      n = num();
                                                                       cmd.add(Integer.toString(n));
      break;
    case STEP:
      jj_consume_token(STEP);
                            cmd.add(token.image);
      jj_consume_token(50);
      n = numVar();
                                                                       cmd.add(Integer.toString(n));
      jj_consume_token(51);
      break;
    case JUMP:
      jj_consume_token(JUMP);
                            cmd.add(token.image);
      jj_consume_token(50);
      n = numVar();
                                                                       cmd.add(Integer.toString(n));
      jj_consume_token(51);
      break;
    case JUMPTO:
      jj_consume_token(JUMPTO);
                              cmd.add(token.image);
      jj_consume_token(50);
      n = numVar();
                                                                         cmd.add(Integer.toString(n));
      jj_consume_token(48);
      m = numVar();
                                                                                                                            cmd.add(Integer.toString(m));
      jj_consume_token(51);
      break;
    case VEER:
      jj_consume_token(VEER);
                            cmd.add(token.image);
      jj_consume_token(50);
      l = saveVeer();
                                                                         cmd.addAll(l);
      jj_consume_token(51);
      break;
    case LOOK:
      jj_consume_token(LOOK);
                            cmd.add(token.image);
      jj_consume_token(50);
      l = saveLook();
                                                                         cmd.addAll(l);
      jj_consume_token(51);
      break;
    case DROP:
      jj_consume_token(DROP);
                            cmd.add(token.image);
      jj_consume_token(50);
      n = numVar();
                                                                       cmd.add(Integer.toString(n));
      jj_consume_token(51);
      break;
    case GRAB:
      jj_consume_token(GRAB);
                            cmd.add(token.image);
      jj_consume_token(50);
      n = numVar();
                                                                       cmd.add(Integer.toString(n));
      jj_consume_token(51);
      break;
    case GET:
      jj_consume_token(GET);
                           cmd.add(token.image);
      jj_consume_token(50);
      n = numVar();
                                                                      cmd.add(Integer.toString(n));
      jj_consume_token(51);
      break;
    case FREE:
      jj_consume_token(FREE);
                            cmd.add(token.image);
      jj_consume_token(50);
      n = numVar();
                                                                       cmd.add(Integer.toString(n));
      jj_consume_token(51);
      break;
    case POP:
      jj_consume_token(POP);
                           cmd.add(token.image);
      jj_consume_token(50);
      n = numVar();
                                                                      cmd.add(Integer.toString(n));
      jj_consume_token(51);
      break;
    case DMOVE:
      jj_consume_token(DMOVE);
                             cmd.add(token.image);
      jj_consume_token(50);
      l = saveDMove();
                                                                           cmd.addAll(l);
      jj_consume_token(51);
      break;
    case OMOVE:
      jj_consume_token(OMOVE);
                             cmd.add(token.image);
      jj_consume_token(50);
      l = saveOMove();
                                                                           cmd.addAll(l);
      jj_consume_token(51);
      break;
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                                                                    {if (true) return cmd;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<String> saveVeer() throws ParseException {
                ArrayList<String> l = new ArrayList<String>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RIGHT:
      jj_consume_token(RIGHT);
                              l.add(token.image);
      break;
    case AROUND:
      jj_consume_token(AROUND);
                              l.add(token.image);
      break;
    case LEFT:
      jj_consume_token(LEFT);
                            l.add(token.image);
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                      {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<String> saveLook() throws ParseException {
                ArrayList<String> l = new ArrayList<String>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NORTH:
      jj_consume_token(NORTH);
                              l.add(token.image);
      break;
    case SOUTH:
      jj_consume_token(SOUTH);
                             l.add(token.image);
      break;
    case EAST:
      jj_consume_token(EAST);
                            l.add(token.image);
      break;
    case WEST:
      jj_consume_token(WEST);
                            l.add(token.image);
      break;
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                       {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<String> saveDMove() throws ParseException {
                Integer n;
                ArrayList<String> l = new ArrayList<String>();
    n = numVar();
                          l.add(Integer.toString(n));
    jj_consume_token(48);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FRONT:
      jj_consume_token(FRONT);
                               l.add(token.image);
      break;
    case RIGHT:
      jj_consume_token(RIGHT);
                              l.add(token.image);
      break;
    case BACK:
      jj_consume_token(BACK);
                             l.add(token.image);
      break;
    case LEFT:
      jj_consume_token(LEFT);
                             l.add(token.image);
      break;
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                        {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<String> saveOMove() throws ParseException {
                Integer n;
                ArrayList<String> l = new ArrayList<String>();
    n = numVar();
                          l.add(Integer.toString(n));
    jj_consume_token(48);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NORTH:
      jj_consume_token(NORTH);
                              l.add(token.image);
      break;
    case SOUTH:
      jj_consume_token(SOUTH);
                             l.add(token.image);
      break;
    case EAST:
      jj_consume_token(EAST);
                            l.add(token.image);
      break;
    case WEST:
      jj_consume_token(WEST);
                            l.add(token.image);
      break;
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                       {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<String> saveCtrlStruct() throws ParseException {
                ArrayList<String> ctrlStruct = new ArrayList<String>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
      ctrlStruct = saveIfFi();
      break;
    case WHILE:
      ctrlStruct = saveWhileDoOd();
      break;
    case REPEATTIMES:
      ctrlStruct = saveRepeatTimes();
      break;
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                  {if (true) return ctrlStruct;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<String> saveIfFi() throws ParseException {
                boolean bool;
                ArrayList<String> instrs = new ArrayList<String>();
                ArrayList<String> l = new ArrayList<String>();
    jj_consume_token(IF);
                          instrs.add(token.image);
    jj_consume_token(50);
    bool = condition();
    jj_consume_token(51);
    jj_consume_token(52);
    l = saveInstrIf(bool);
                                                    instrs.addAll(l);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 49:
        ;
        break;
      default:
        jj_la1[30] = jj_gen;
        break label_11;
      }
      jj_consume_token(49);
      l = saveInstrIf(bool);
                                                                                                      instrs.addAll(l);
    }
    jj_consume_token(53);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      jj_consume_token(52);
      l = saveInstrIf(!bool);
                                                     instrs.addAll(l);
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 49:
          ;
          break;
        default:
          jj_la1[31] = jj_gen;
          break label_12;
        }
        jj_consume_token(49);
        l = saveInstrIf(!bool);
                                                                                                        instrs.addAll(l);
      }
      jj_consume_token(53);
      break;
    default:
      jj_la1[32] = jj_gen;
      ;
    }
    jj_consume_token(FI);
                this.salida = this.salida + "\u005cn'if' conditional control structure";
                {if (true) return instrs;}
    throw new Error("Missing return statement in function");
  }

  private ArrayList<String> saveInstrIf(boolean bool) throws ParseException {
                ArrayList<String> l = new ArrayList<String>();
                if (bool) {
                        l = saveInstr();
                } else {
                        checkSintaxInstr();
                }
                return l;
  }

  final public ArrayList<String> saveWhileDoOd() throws ParseException {
                boolean bool;
                ArrayList<String> l = new ArrayList<String>();
    jj_consume_token(WHILE);
    jj_consume_token(50);
    bool = condition();
    jj_consume_token(51);
    jj_consume_token(DO);
    jj_consume_token(OD);
                        this.salida = this.salida + "\u005cn'while' loop control structure";
                        {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<String> saveRepeatTimes() throws ParseException {
                Integer n;
                ArrayList<String> l = new ArrayList<String>();
    jj_consume_token(REPEATTIMES);
    n = numVar();
    jj_consume_token(PER);
                        this.salida = this.salida + "\u005cn'repeatTimes' loop control structure";
                        {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<String> saveProcCall() throws ParseException {
                String name;
                ArrayList<String> rParams = new ArrayList<String>();
    name = name();
    jj_consume_token(50);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      rParams = params();
      break;
    default:
      jj_la1[33] = jj_gen;
      ;
    }
    jj_consume_token(51);
                        if (!procsNames.contains(name)) {
                                {if (true) throw new Error("Tried to call undeclared procedure");}
                        }
                        if (rParams.size() != procsParams.get(name).size()) {
                                {if (true) throw new Error("Incorrect number of parameters for "+name+" procedure");}
                        }
                        // TODO: Guardar el llamado del procedimiento

    throw new Error("Missing return statement in function");
  }

  final public void checkSintaxInstr() throws ParseException {
    if (jj_2_6(2)) {
      checkSintaxCmd();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case REPEATTIMES:
        checkSintaxCtrlStruct();
        break;
      case NAME:
        checkSintaxProcCall();
        break;
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void checkSintaxCmd() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      jj_consume_token(NAME);
      jj_consume_token(54);
      jj_consume_token(NUM);
      break;
    case STEP:
      jj_consume_token(STEP);
      jj_consume_token(50);
      numVar();
      jj_consume_token(51);
      break;
    case JUMP:
      jj_consume_token(JUMP);
      jj_consume_token(50);
      numVar();
      jj_consume_token(51);
      break;
    case JUMPTO:
      jj_consume_token(JUMPTO);
      jj_consume_token(50);
      numVar();
      jj_consume_token(48);
      numVar();
      jj_consume_token(51);
      break;
    case VEER:
      jj_consume_token(VEER);
      jj_consume_token(50);
      veer();
      jj_consume_token(51);
      break;
    case LOOK:
      jj_consume_token(LOOK);
      jj_consume_token(50);
      look();
      jj_consume_token(51);
      break;
    case DROP:
      jj_consume_token(DROP);
      jj_consume_token(50);
      numVar();
      jj_consume_token(51);
      break;
    case GRAB:
      jj_consume_token(GRAB);
      jj_consume_token(50);
      numVar();
      jj_consume_token(51);
      break;
    case GET:
      jj_consume_token(GET);
      jj_consume_token(50);
      numVar();
      jj_consume_token(51);
      break;
    case FREE:
      jj_consume_token(FREE);
      jj_consume_token(50);
      numVar();
      jj_consume_token(51);
      break;
    case POP:
      jj_consume_token(POP);
      jj_consume_token(50);
      numVar();
      jj_consume_token(51);
      break;
    case DMOVE:
      jj_consume_token(DMOVE);
      jj_consume_token(50);
      dMove();
      jj_consume_token(51);
      break;
    case OMOVE:
      jj_consume_token(OMOVE);
      jj_consume_token(50);
      oMove();
      jj_consume_token(51);
      break;
    default:
      jj_la1[35] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void checkSintaxCtrlStruct() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
      checkSintaxifFi();
      break;
    case WHILE:
      checkSintaxwhileDoOd();
      break;
    case REPEATTIMES:
      checkSintaxrepeatTimes();
      break;
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void checkSintaxifFi() throws ParseException {
                boolean bool;
    jj_consume_token(IF);
    jj_consume_token(50);
    condition();
    jj_consume_token(51);
    checkSintaxInstrBlock();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      checkSintaxInstrBlock();
      break;
    default:
      jj_la1[37] = jj_gen;
      ;
    }
    jj_consume_token(FI);
  }

  final public void checkSintaxwhileDoOd() throws ParseException {
    jj_consume_token(WHILE);
    jj_consume_token(50);
    condition();
    jj_consume_token(51);
    jj_consume_token(DO);
    checkSintaxInstrBlock();
    jj_consume_token(OD);
  }

  final public void checkSintaxProcCall() throws ParseException {
    name();
    jj_consume_token(50);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      params();
      break;
    default:
      jj_la1[38] = jj_gen;
      ;
    }
    jj_consume_token(51);
  }

  final public void checkSintaxrepeatTimes() throws ParseException {
    jj_consume_token(REPEATTIMES);
    numVar();
    checkSintaxInstrBlock();
    jj_consume_token(PER);
  }

  final public String name() throws ParseException {
    jj_consume_token(NAME);
                           {if (true) return token.image;}
    throw new Error("Missing return statement in function");
  }

        /**
	 * Unsigned decimal number
	 * @return the corresponding value of the string
	 * @error  corresponding value is too large
	 */
  final public Integer num() throws ParseException, Error {
                int total_;
                Integer total;
    jj_consume_token(NUM);
                        try
                        {
                                total_ = Integer.parseInt(token.image);
                                total = Integer.valueOf(total_);
                        }
                        catch (NumberFormatException ee)
                        {
                                {if (true) throw new Error("Number out of bounds: "+token.image);}
                        }
                        {if (true) return total;}
    throw new Error("Missing return statement in function");
  }

  final public Integer numVar() throws ParseException, Error {
                int total_;
                Integer total;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUM:
      jj_consume_token(NUM);
                        try
                        {
                                total_ = Integer.parseInt(token.image);
                                total = Integer.valueOf(total_);
                        }
                        catch (NumberFormatException ee)
                        {
                                {if (true) throw new Error("Number out of bounds: "+token.image);}
                        }
      break;
    case NAME:
      jj_consume_token(NAME);
                        if (vars.containsKey(token.image)) {
                                total_ = vars.get(token.image);
                                total = Integer.valueOf(total_);
                        } else {
                                {if (true) throw new Error("Tried to use undeclared variable");}
                        }
      break;
    default:
      jj_la1[39] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                       {if (true) return total;}
    throw new Error("Missing return statement in function");
  }

  final public Integer numVarParam(Hashtable<String, Integer> procParams) throws ParseException, Error {
                int total_;
                Integer total;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUM:
      jj_consume_token(NUM);
                        try
                        {
                                total_ = Integer.parseInt(token.image);
                                total = Integer.valueOf(total_);
                        }
                        catch (NumberFormatException ee)
                        {
                                {if (true) throw new Error("Number out of bounds: "+token.image);}
                        }
      break;
    case NAME:
      jj_consume_token(NAME);
                        if (procParams.containsKey(token.image)) {
                                total = procParams.get(token.image);
                        }
                        else if (vars.containsKey(token.image)) {
                                total = vars.get(token.image);
                        } else {
                                {if (true) throw new Error("Tried to use unexsiting parameter or undeclared variable");}
                        }
      break;
    default:
      jj_la1[40] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                       {if (true) return total;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_3R_31() {
    if (jj_scan_token(DMOVE)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_scan_token(POP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(FREE)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(GET)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(GRAB)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(DROP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(LOOK)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(VEER)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_scan_token(JUMPTO)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_scan_token(JUMP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(OMOVE)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_scan_token(STEP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(DMOVE)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_scan_token(POP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_scan_token(FREE)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_scan_token(GET)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_scan_token(GRAB)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(DROP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(LOOK)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_scan_token(VEER)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(54)) return true;
    return false;
  }

  private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(JUMPTO)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_scan_token(JUMP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(STEP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_scan_token(NAME)) return true;
    if (jj_scan_token(54)) return true;
    return false;
  }

  private boolean jj_3R_17() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(49)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_3R_60()) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_3R_59()) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_scan_token(REPEATTIMES)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(48)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_scan_token(WHILE)) return true;
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_scan_token(NAME)) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_scan_token(IF)) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_scan_token(OMOVE)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(DMOVE)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_scan_token(POP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(FREE)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_scan_token(GET)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_3R_66()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(GRAB)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(DROP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_3R_64()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_scan_token(LOOK)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(48)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_scan_token(VEER)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(JUMPTO)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(JUMP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_scan_token(NAME)) return true;
    if (jj_scan_token(54)) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(STEP)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_scan_token(OMOVE)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public RobotTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[41];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x1,0x0,0x920000,0x1ffe0,0x920000,0x0,0x0,0x80000,0x1e000000,0x0,0x0,0xc0000000,0x0,0xc0000000,0xc0000000,0x20006c60,0xc0000000,0x0,0x0,0x0,0x0,0x920000,0x1ffe0,0x0,0xc0000000,0x0,0xc0000000,0x920000,0x0,0x0,0x80000,0x0,0x920000,0x1ffe0,0x920000,0x80000,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x200,0x400,0x80,0x1000,0x1000,0x1000,0x0,0x20000,0x20000,0x0,0x0,0x1000,0x1c,0x3,0x78,0x3,0x3,0x0,0x3,0x20000,0x20000,0x20000,0x20000,0x1000,0x1000,0x1c,0x3,0x78,0x3,0x0,0x20000,0x20000,0x0,0x1000,0x1000,0x1000,0x0,0x0,0x1000,0x5000,0x5000,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[6];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Robot(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Robot(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new RobotTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Robot(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new RobotTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Robot(RobotTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(RobotTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[55];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 41; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 55; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 6; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
