/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STEP = 5;
  /** RegularExpression Id. */
  int JUMP = 6;
  /** RegularExpression Id. */
  int JUMPTO = 7;
  /** RegularExpression Id. */
  int VEER = 8;
  /** RegularExpression Id. */
  int LOOK = 9;
  /** RegularExpression Id. */
  int DROP = 10;
  /** RegularExpression Id. */
  int GRAB = 11;
  /** RegularExpression Id. */
  int GET = 12;
  /** RegularExpression Id. */
  int FREE = 13;
  /** RegularExpression Id. */
  int POP = 14;
  /** RegularExpression Id. */
  int DMOVE = 15;
  /** RegularExpression Id. */
  int OMOVE = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int FI = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int OD = 22;
  /** RegularExpression Id. */
  int REPEATTIMES = 23;
  /** RegularExpression Id. */
  int PER = 24;
  /** RegularExpression Id. */
  int ISFACING = 25;
  /** RegularExpression Id. */
  int ISVALID = 26;
  /** RegularExpression Id. */
  int CANMOVE = 27;
  /** RegularExpression Id. */
  int NOT = 28;
  /** RegularExpression Id. */
  int PICK = 29;
  /** RegularExpression Id. */
  int NORTH = 30;
  /** RegularExpression Id. */
  int SOUTH = 31;
  /** RegularExpression Id. */
  int EAST = 32;
  /** RegularExpression Id. */
  int WEST = 33;
  /** RegularExpression Id. */
  int AROUND = 34;
  /** RegularExpression Id. */
  int RIGHT = 35;
  /** RegularExpression Id. */
  int LEFT = 36;
  /** RegularExpression Id. */
  int FRONT = 37;
  /** RegularExpression Id. */
  int BACK = 38;
  /** RegularExpression Id. */
  int PROG = 39;
  /** RegularExpression Id. */
  int GORP = 40;
  /** RegularExpression Id. */
  int VAR = 41;
  /** RegularExpression Id. */
  int PROC = 42;
  /** RegularExpression Id. */
  int CORP = 43;
  /** RegularExpression Id. */
  int NAME = 44;
  /** RegularExpression Id. */
  int LETTER = 45;
  /** RegularExpression Id. */
  int NUM = 46;
  /** RegularExpression Id. */
  int DIGIT = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"step\"",
    "\"jump\"",
    "\"jumpTo\"",
    "\"veer\"",
    "\"look\"",
    "\"drop\"",
    "\"grab\"",
    "\"get\"",
    "\"free\"",
    "\"pop\"",
    "\"Dmove\"",
    "\"Omove\"",
    "\"if\"",
    "\"fi\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"od\"",
    "\"repeatTimes\"",
    "\"per\"",
    "\"isfacing\"",
    "\"isValid\"",
    "\"canMove\"",
    "\"not\"",
    "\"pick\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "\"around\"",
    "\"right\"",
    "\"left\"",
    "\"front\"",
    "\"back\"",
    "\"PROG\"",
    "\"GORP\"",
    "\"VAR\"",
    "\"PROC\"",
    "\"CORP\"",
    "<NAME>",
    "<LETTER>",
    "<NUM>",
    "<DIGIT>",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\":=\"",
  };

}
